USE [master]
GO
ALTER DATABASE [LOCAL-QUFIB-TEST] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

USE [master]
RESTORE DATABASE [LOCAL-QUFIB-TEST] FROM  DISK = N'C:\FILEDATA\BACKS\QUFIBHourDiff.bak' WITH  FILE = 1,  
	MOVE N'qufib' TO N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\LOCAL-QUFIB-TEST.mdf',  
	MOVE N'qufib_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\LOCAL-QUFIB-TEST_log.ldf',  RECOVERY,  NOUNLOAD,  REPLACE,  STATS = 5

GO

USE [master]
GO
ALTER DATABASE [LOCAL-QUFIB-TEST] SET  MULTI_USER
GO